version: '3'
services:
    weatherfrontend:
      image: ollieflld/weatherfrontend:latest
      container_name: weatherfrontend
      restart: 'unless-stopped'
      environment:
        BACKEND_URL: "192.168.0.23:18080"